# $OpenBSD$

COMMENT =	Brainfuck compiler in C
DISTNAME =	bfc-1.1
CATEGORIES =	lang

HOMEPAGE =	https://devio.us/~bcallah/bfc/
MAINTAINER =	Your Name <you@example.com>

# ISC
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

MASTER_SITES =	https://github.com/ibara/bfc/releases/download/${DISTNAME}/

CONFIGURE_STYLE =	simple

NO_TEST =	Yes

.include <bsd.port.mk>
