# $OpenBSD$

COMMENT =	randomly permute input lines
DISTNAME =	shuf-2.0
CATEGORIES =	sysutils

HOMEPAGE =	https://devio.us/~bcallah/shuf/
MAINTAINER =	Your Name <you@example.com>

# ISC
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

MASTER_SITES =	https://github.com/ibara/shuf/releases/download/${DISTNAME}/

CONFIGURE_STYLE =	simple

NO_TEST =	Yes

.include <bsd.port.mk>
