# $OpenBSD$

ONLY_FOR_ARCHS =	${GO_ARCHS}

COMMENT =	Unix shell with Scheme-like programming language
CATEGORIES =	shells

GH_ACCOUNT =	michaelmacinnis
GH_PROJECT =	oh
GH_TAGNAME =	

HOMEPAGE =	https://github.com/michaelmacinnis/oh
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# MIT
PERMIT_PACKAGE_CDROM =	Yes

#WANTLIB +=	c pthread

MODULES =	lang/go

.include <bsd.port.mk>
