# $OpenBSD$

V =		0.5.32.7
COMMENT =	Python 2 and 3 compatible compiler
DISTNAME =	Nuitka-${V}
PKGNAME =	nuitka-${V}
CATEGORIES =	lang

HOMEPAGE =	https://nuitka.net/
MAINTAINER =	Brian Callahan <bcallah@openbsd.org>

# Apache 2.0
PERMIT_PACKAGE_CDROM =	Yes

#WANTLIB = ${COMPILER_LIBCXX} c m

MASTER_SITES =	https://nuitka.net/releases/

MODULES =	lang/python

.include <bsd.port.mk>
